### ISSUE TITLE
[meta] Finish WebSocket rewrite

### ISSUE THREAD

**Issue by alicoding** [mozilla/makedrive#2]
- [x] [issue #10] Re-implement server-side server-to-client syncing through a Websocket
- [x] [issue #9] Implement server-side client-to-server syncing through a Websocket
- [x] [issue #33] Add final step in downstream sync to client code
