### ISSUE TITLE
[meta] Write tests for WebSocket protocol

### ISSUE THREAD

**Issue by alicoding** [mozilla/makedrive#4]
- [ ] [issue #11] Server-side client-to-server protocol testing
- [x] [issue #12] Server-side server-to-client protocol testing 
- [ ] [issue #13] Client-side client-to-server protocol testing
- [ ] [issue #14] Client-side server-to-client protocol testing
